name: Tache_3

on:
  push:
  pull_request:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 22

defaults:
  run:
    shell: bash
    

jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flag: ["-XX:+ExtensiveErrorReports"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          
      - name: Buid first flag
        run: |
          export MAVEN_OPTS=${{ matrix.flag }}
          echo "###############################"
          echo $MAVEN_OPTS
          echo "###############################"
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage
          unset MAVEN_OPTS
